ALTER TABLE `users`
ADD COLUMN IF NOT EXISTS `verificationRequired` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `verificationContext` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `verificationOtp` INT NULL,
ADD COLUMN IF NOT EXISTS `verificationOtpExpiresAt` DATETIME NULL;

ALTER TABLE `accounts`
ADD COLUMN IF NOT EXISTS `verificationRequired` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `verificationContext` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `verificationOtp` INT NULL,
ADD COLUMN IF NOT EXISTS `verificationOtpExpiresAt` DATETIME NULL;

ALTER TABLE `salesReps`
ADD COLUMN IF NOT EXISTS `verificationRequired` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `verificationContext` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `verificationOtp` INT NULL,
ADD COLUMN IF NOT EXISTS `verificationOtpExpiresAt` DATETIME NULL;

ALTER TABLE `supplier`
ADD COLUMN IF NOT EXISTS `verificationRequired` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `verificationContext` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `verificationOtp` INT NULL,
ADD COLUMN IF NOT EXISTS `verificationOtpExpiresAt` DATETIME NULL;

ALTER TABLE `employees`
ADD COLUMN IF NOT EXISTS `verificationRequired` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `verificationContext` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `verificationOtp` INT NULL,
ADD COLUMN IF NOT EXISTS `verificationOtpExpiresAt` DATETIME NULL;
