ALTER TABLE `users`
ADD COLUMN IF NOT EXISTS `loginVerificationDone` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `accounts`
ADD COLUMN IF NOT EXISTS `loginVerificationDone` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `salesReps`
ADD COLUMN IF NOT EXISTS `loginVerificationDone` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `supplier`
ADD COLUMN IF NOT EXISTS `loginVerificationDone` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `employees`
ADD COLUMN IF NOT EXISTS `loginVerificationDone` TINYINT(1) NOT NULL DEFAULT 0;
