CREATE TABLE IF NOT EXISTS `landing_pages` (
  `id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `status` ENUM('draft','published','scheduled','archived') NOT NULL DEFAULT 'draft',
  `template_id` VARCHAR(64) NULL,
  `campaign_name` VARCHAR(255) NULL,
  `objective` VARCHAR(500) NULL,
  `target_audience` VARCHAR(500) NULL,
  `city` VARCHAR(100) NULL,
  `draft_sections` JSON NOT NULL,
  `published_sections` JSON NULL,
  `seo` JSON NOT NULL,
  `tracking` JSON NOT NULL,
  `form_settings` JSON NOT NULL,
  `preview_token` VARCHAR(128) NOT NULL,
  `published_url` VARCHAR(500) NULL,
  `published_at` DATETIME NULL,
  `scheduled_at` DATETIME NULL,
  `unpublish_at` DATETIME NULL,
  `archived_at` DATETIME NULL,
  `created_by` VARCHAR(64) NULL,
  `updated_by` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `landing_pages_slug_unique` (`slug`),
  KEY `landing_pages_status_idx` (`status`),
  KEY `landing_pages_preview_token_idx` (`preview_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
