CREATE TABLE IF NOT EXISTS `media_assets` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('image','video','document') NOT NULL,
  `alt_text` VARCHAR(500) NULL,
  `url` VARCHAR(2000) NOT NULL,
  `mime_type` VARCHAR(128) NULL,
  `file_size_bytes` INT NULL,
  `approved` TINYINT(1) NOT NULL DEFAULT 1,
  `is_builtin` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
