CREATE TABLE IF NOT EXISTS `marketing_touchpoints` (
  `id` VARCHAR(80) NOT NULL,
  `visitor_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `source` VARCHAR(255) NOT NULL DEFAULT 'direct',
  `medium` VARCHAR(255) NOT NULL DEFAULT '',
  `campaign` VARCHAR(255) NOT NULL DEFAULT '',
  `content` VARCHAR(255) NOT NULL DEFAULT '',
  `term` VARCHAR(255) NOT NULL DEFAULT '',
  `referrer` VARCHAR(2000) NOT NULL DEFAULT '',
  `landing_page` VARCHAR(200) NULL,
  `landing_page_id` VARCHAR(64) NULL,
  `page_url` VARCHAR(2000) NULL,
  `pathname` VARCHAR(500) NULL,
  `page_title` VARCHAR(500) NULL,
  `category` VARCHAR(64) NULL,
  `click_ids` JSON NULL,
  `is_landing_page` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `marketing_touchpoints_visitor_idx` (`visitor_id`),
  KEY `marketing_touchpoints_session_idx` (`session_id`),
  KEY `marketing_touchpoints_timestamp_idx` (`timestamp`),
  KEY `marketing_touchpoints_landing_page_idx` (`landing_page`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
