name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - testing
      - aws-prod

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.20.4

    steps:
      - uses: actions/checkout@v2

  deploy_main:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Check deployment flag
        run: |
          DEPLOY_FLAG="yes"
          if [ "$DEPLOY_FLAG" != "yes" ]; then
            exit 0
          fi

      - name: Create .env file dynamically
        run: echo "${{ secrets.ENV_FILE_CONTENT_PROD }}" > .env

      - name: Create config folder and files
        run: |
          mkdir -p config
          echo "${{ secrets.CONFIG_JSON_CONTENT_PROD }}" > config/config.json

      - name: Create .htaccess file
        run: echo "${{ secrets.HTACCESS_CONTENT_PROD }}" > .htaccess

      - name: Create firebase.json file
        run: echo "${{ secrets.FIREBASE_CONTENT_PROD }}" > firebase.json

      - name: 📂 Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ${{ secrets.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          timeout: 420

      - name: Trigger npm install on server
        run: curl -X GET "https://backendbb.trimworldwide.com/trigger.php"

  deploy_testing:
    needs: build
    if: github.ref == 'refs/heads/testing'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT_STAGE }}" > .env

      - name: Create config folder
        run: |
          mkdir -p config
          echo "${{ secrets.CONFIG_JSON_CONTENT_STAGE }}" > config/config.json

      - name: Create .htaccess file
        run: echo "${{ secrets.HTACCESS_CONTENT_STAGE }}" > .htaccess

      - name: Create firebase.json file
        run: echo "${{ secrets.FIREBASE_CONTENT_STAGE }}" > firebase.json

      - name: 📂 Sync files to staging
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ${{ secrets.STAGE_FTP_HOST }}
          username: ${{ secrets.STAGE_FTP_USERNAME }}
          password: ${{ secrets.STAGE_FTP_PASSWORD }}
          timeout: 560

      - name: Trigger npm install on server
        run: curl -X GET "https://testingbb.trimworldwide.com/trigger.php"

  deploy_aws_prod:
    needs: build
    if: github.ref == 'refs/heads/aws-prod'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: busybeans
      ECS_CLUSTER: busybeancoffee
      ECS_SERVICE: busybeans-backend
      TASK_DEFINITION: task-definition-busybeans
      CONTAINER_NAME: busybeans-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +'%Y%m%d%H%M%S')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Register New Task Definition
        run: |
          NEW_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          TASK_DEF=$(aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION }})
          NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$NEW_IMAGE_URI" \
            '.taskDefinition
            | .containerDefinitions[0].image=$IMAGE
            | del(.status,.revision,.taskDefinitionArn,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)')
          echo "$NEW_TASK_DEF" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.TASK_DEFINITION }} \
            --force-new-deployment


            